version: '3'

services:
  frontend:
    restart: always
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: npm start
    volumes:
      - ./frontend/src:/frontend/src
    
  backend:
    restart: always
    container_name: backend
    build:
      context: ./
    ports:
      - "8000:8000"
    volumes:
      - ./:/backend
    environment:
      SECRET_KEY: "DOCKER"
      DB_NAME: "face_detection"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_HOST: "db"
      DB_PORT: 5432
      DEBUG: "1"
    command: bash -c "python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_DB: face_detection
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres_data: