version: '3'

services:
  frontend:
    restart: always
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: npm start
    volumes:
      - ./frontend/src:/frontend/src
    
  backend:
    restart: always
    container_name: backend
    build:
      context: ./
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: "DOCKER"
    command: python -m manage runserver 0.0.0.0:8000