# Generated by Django 4.0.3 on 2022-06-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_face_landmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='landmarks',
            field=models.JSONField(default=dict),
        ),
    ]
