# Generated by Django 4.0.3 on 2022-06-03 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_face_landmarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=200)),
                ('image', models.TextField(blank=True, max_length=512)),
                ('processedImage', models.TextField(blank=True, max_length=512)),
                ('originalPublicId', models.TextField(blank=True, max_length=512)),
                ('processedPublicId', models.TextField(blank=True, max_length=512)),
                ('isLive', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('landmarks', models.JSONField(default=dict)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Face',
        ),
    ]
