# Generated by Django 4.0.3 on 2022-03-28 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_face_processed_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='face',
            old_name='_id',
            new_name='id',
        ),
    ]
