# Generated by Django 4.0.3 on 2022-04-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_face_id_alter_face_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='public_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
