# Generated by Django 4.0.3 on 2022-04-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_face_public_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='face',
            old_name='public_id',
            new_name='originalPublicId',
        ),
        migrations.AddField(
            model_name='face',
            name='processedPublicId',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
