on: push
jobs:
  postgres-job:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
    container: python:3.9

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres_db
          POSTGRES_PASSWORD: postgres_password
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres_user
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Set up Python 3.9
        uses: actions/checkout@v2
        with:
          python-version: 3.9
      - name: Install PostgreSQL client
        run: |
          apt-get update
          apt-get install --yes postgresql-client
      - name: Query database
        run: psql -h postgres -d postgres_db -U postgres_user -c 'SELECT 1;'
        env:
          PGPASSWORD: postgres_password

      - name: Install Dependencies
        run: |
          apt install -y python3-pip
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          python3 manage.py test && flake8
        env:
          PGPASSWORD: postgres_password
          SECRET_KEY: CI
          DB_PASSWORD: postgres_password
          DB_USER: postgres_user
          DB_NAME: postgres_db
          DB_HOST: postgres
          DB_PORT: 5432
          cloud_name: TEST_NAME
          api_key: TEST_KEY
          api_secret: TEST_SECRET
          PROD: 0
          DEBUG: "1"
          CSRF_TRUSTED_ORIGINS: http://backend:8000/