on: push
jobs:
  postgres-job:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
    container: node:latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
        with:
          requirement_files: requirements.txt

      - uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      - uses: actions/checkout@v2
      - uses: Dovyski/setup-opencv-action@v1
        with:
          opencv-version: '4.0.0'
      - name: Run Tests
        run: |
          python3 manage.py test && flake8
        env:
          SECRET_KEY: CI
